[package]
name = "wakeonlan"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
codegen-units = 1
debug = "full"
lto = true
opt-level = "s"
panic = "abort"
split-debuginfo = "packed"
strip = "symbols"
incremental = true
